---
- hosts: servers


  tasks:

    - name: "Yarn | GPG"
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: present


    - name: "Yarn | Ensure Debian sources list file exists"
      file:
        path: /etc/apt/sources.list.d/yarn.list
        owner: root
        mode: 0644
        state: touch


    - name: "Yarn | Ensure Debian package is in sources list"
      lineinfile:
        dest: /etc/apt/sources.list.d/yarn.list
        regexp: 'deb http://dl.yarnpkg.com/debian/ stable main'
        line: 'deb http://dl.yarnpkg.com/debian/ stable main'
        state: present


    - name: "Update APT cache"
      apt:
        update_cache: yes


    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest          


    - name: "Install CURL"
      apt:
        pkg:
          - curl


    - name: Execute script to add NodeJS to repository
      shell:
        "curl -fsSL https://deb.nodesource.com/setup_22.x | sudo bash - "


    - name: Install needed software
      apt: 
        pkg: 
          - git
          - yarn
          - nodejs
#          - npm
          - python3
          - python3-pip

    - name: "Install Docker"
      include_role:
        name: geerlingguy.docker
